services:
  xuad_blog_extension.listener.parse_article_list:
    class: Xuad\BlogBundle\EventListener\ParseArticleListListener
    arguments:
    - "@xuad_blog_extension.service.parse_article_list_service"