services:
  xuad_blog.repository.news_archive_repository:
    class: Xuad\BlogBundle\Repository\NewsArchiveRepository
  xuad_blog.service.module_news_archive_service:
    class: Xuad\BlogBundle\Service\ModuleNewsArchiveService
    arguments:
      - "@xuad_blog.repository.news_archive_repository"
      - "@contao.routing.url_generator"
  xuad_blog.service.parse_article_list_service:
    class: Xuad\BlogBundle\Service\ParseArticleListService
    arguments:
      - "@xuad_blog.repository.news_archive_repository"
  xuad_blog.service.module_news_list_service:
    class: Xuad\BlogBundle\Service\ModuleNewsListService
    arguments:
      - "@xuad_blog.repository.news_archive_repository"
  xuad_blog.service.news_archive_backend_service:
    class: Xuad\BlogBundle\Service\NewsArchiveBackendService
    arguments:
      - "@xuad_blog.repository.news_archive_repository"

# Entity service
  xuad_blog.service.entity.news_archive_entity_service:
    class: Xuad\BlogBundle\Service\Entity\NewsArchiveEntityService
    arguments:
      - "@xuad_blog.repository.news_archive_repository"